CREATE TABLE public.headway_candles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  symbol text NOT NULL CHECK (symbol IN ('VOL_10', 'VOL_20')),
  timeframe integer NOT NULL CHECK (timeframe IN (60, 300, 900, 3600)),
  epoch bigint NOT NULL CHECK (epoch > 0),
  open double precision NOT NULL,
  high double precision NOT NULL,
  low double precision NOT NULL,
  close double precision NOT NULL,
  volume double precision NOT NULL DEFAULT 0,
  received_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT headway_candles_ohlc_valid CHECK (
    high >= low AND high >= open AND high >= close AND low <= open AND low <= close
  ),
  CONSTRAINT headway_candles_unique_bar UNIQUE (symbol, timeframe, epoch)
);

GRANT SELECT ON public.headway_candles TO anon, authenticated;
GRANT ALL ON public.headway_candles TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.headway_candles_id_seq TO service_role;

ALTER TABLE public.headway_candles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can read Headway market candles"
ON public.headway_candles
FOR SELECT
TO anon, authenticated
USING (true);

CREATE INDEX headway_candles_lookup_idx
ON public.headway_candles (symbol, timeframe, epoch DESC);

ALTER PUBLICATION supabase_realtime ADD TABLE public.headway_candles;